### ISSUE TITLE
Misalignment in the X button

### ISSUE THREAD

**Issue by neokore** [GeographicaGS/cartodb-geoprocessing-tools#61]
![image](https://cloud.githubusercontent.com/assets/938057/16237023/d479f1ac-37da-11e6-9d1e-02c004f3c76a.png)

**Comment by neokore** [comment]
Possibly it is related to CartoDB. I'll check it.

**Comment by alasarr** [comment]
Yes, it's look like a CatoDB issue. We can do nothing here.

**Comment by neokore** [comment]
I've applied a workaround to fix this button appearance.
